### ISSUE TITLE
Common crash report for all crashes - Rx v3.0.4 + RxDogTag v2.0.1

### ISSUE THREAD

**Issue by droid-it** [uber/RxDogTag#71]
**Library version**: 2.0.1

**Repro steps or stacktrace**:

Crash 1: 

```
Caused by java.lang.NumberFormatException: For input string: ""
       at rxdogtag2.-$$Lambda$RxDogTag$YP26HIb1nhHqbV4QlRgnyBuwHqU.apply(-.java:6)
       at [[ ↑↑ Inferred subscribe point ↑↑ ]].([[ ↑↑ Inferred subscribe point ↑↑ ]].java)
       at [[ Originating callback: onNext ]].([[ Originating callback: onNext ]].java)
       at [[ ↓↓ Original trace ↓↓ ]].([[ ↓↓ Original trace ↓↓ ]].java)
       at java.lang.Integer.parseInt(Integer.java:627)
       at java.lang.Integer.parseInt(Integer.java:650)
       at .....

```

Crash 2:
```
Caused by java.lang.IllegalArgumentException: No enum constant x.y.z.ECONOMY
       at rxdogtag2.-$$Lambda$RxDogTag$YP26HIb1nhHqbV4QlRgnyBuwHqU.apply(-.java:6)
       at [[ ↑↑ Inferred subscribe point ↑↑ ]].([[ ↑↑ Inferred subscribe point ↑↑ ]].java)
       at [[ Originating callback: onNext ]].([[ Originating callback: onNext ]].java)
       at [[ ↓↓ Original trace ↓↓ ]].([[ ↓↓ Original trace ↓↓ ]].java)
       at java.lang.Enum.valueOf(Enum.java:257)
```

both have the common line
       at rxdogtag2.-$$Lambda$RxDogTag$YP26HIb1nhHqbV4QlRgnyBuwHqU.apply(-.java:6)

which is causing all crashes to merge under a single report

**Comment by ZacSweers** [comment]
This isn't enough detail to be able to help you. Feel free to revisit when you have more information, such as a minimal reproducible sample project.
